### ISSUE TITLE
Merge with other attempt to maintain LNI class

### ISSUE THREAD

**Issue by koppor** [latextemplates/LNI#2]
@sieversMartin is in parallel creating an updated version of the template at https://github.com/sieversMartin/LNI.

I am in contact with him to join forces. This issue is created to make other interested persons aware of that.

**Comment by stefan-balke** [comment]
Hi,
is this somehow coordinated with the GI?

Maybe they want to update their templates?

- Stefan

**Comment by sieversMartin** [comment]
I am working "officially" on the template. I did, however, try to add things from @koppor . As a second steps the template should be maintained by experienced users IMHO. However, this has to be discussed with the GI's representatives.

**Comment by stefan-balke** [comment]
Okay, cool! I see that you did already change things in your repo. Is it planned to exchange the version on the GI website or even give a link to a github repo?

**Comment by sieversMartin** [comment]
My version is going to become the official version. However, as I said, I'd like to see the community maintain and develop it. My work is limited to a technical rework, not necessarily a complete layout rework etc.

**Comment by stefan-balke** [comment]
Well, I think the layout is fine for now.

>  However, as I said, I'd like to see the community maintain and develop it.
This it then +1 for GitHub.

Any dates for the update available? I'm asking since we organize a workshop for the Informatik 2017 and we'll want to link to the template.
The current version has all kinds of drawbacks besides being not UTF-8...

**Comment by koppor** [comment]
On the GI conference [BTW 2017](http://btw2017.informatik.uni-stuttgart.de/) we are pointing the authors to https://github.com/latextemplates/LNI. Some are complaining because of biber, but most of them are using the template. For the ones not willing to switch, we offer https://github.com/latextemplates/LNI/tree/lni-bibtex

Further, UTF-8 is enabled in both branches: https://github.com/latextemplates/LNI/blob/lni-bibtex/paper.tex#L33

(I am the one responsible to generate the proceedings for the conference. The final PDFs will be reviewed by the GI at the second week of January)

The GI also told me to get in touch with @sieversMartin. We have tried his development version for a paper and it worked fine besides bibtex. See https://github.com/sieversMartin/LNI/issues/6.

**Comment by koppor** [comment]
I am willing to give up my improved version in favor of an official one.

The difference to the last official one (and not the one at https://github.com/sieversMartin/LNI/) are listed at https://github.com/latextemplates/LNI/#benefits-in-comparison-to-gi-evs-version. You will note that there is no adjustment of the layout.

I hope to find some time to document the differences with https://github.com/sieversMartin/LNI/ and to think about whether these should be included or excluded there. And also to document that.

**Comment by koppor** [comment]
I now took the latest `lni.cls` with all pull requests included and offer it here. Will keep it updated. So this issue can be closed.
